{{- if and .Values.persistence.enabled (not .Values.persistence.existingClaim) }}
kind: PersistentVolume
apiVersion: v1
metadata:
  name: {{ template "airflow.fullname" . }}
spec:
  accessModes:
    - {{ .Values.persistence.accessMode | quote }}
  capacity:
    storage: {{ .Values.persistence.size | quote }}
  nfs:
    server: {{ .Values.persistence.nfsServer }}
    path: {{ .Values.persistence.nfsMountPath }}
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ template "airflow.fullname" . }}
  annotations:
    volume.beta.kubernetes.io/storage-class: ""
  labels:
    app: {{ template "airflow.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  accessModes:
    - {{ .Values.persistence.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.persistence.size | quote }}
{{- end }}