apiVersion: v1
kind: Secret
metadata:
  name: airflow-secrets
  labels:
    app: {{ template "airflow.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  sql_alchemy_conn:  {{ .Values.secrets.sqlAlchemyConn | b64enc | quote }}